name: default

on:
  create:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  docker:
    needs: ['build']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Find Tag
      id: tagger
      uses: jimschubert/query-tag-action@v2
      with:
        include: 'v*'
        commit-ish: 'HEAD'
        abbrev: false

    - name: Show Tag
      id: display
      run: |
        echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: confinale/medea:${{steps.tagger.outputs.tag}}
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}



  
  autodeploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest
    needs: ['docker','build']

    steps:
    - uses: actions/checkout@v2
    - name: Find Tag
      id: tagger
      uses: jimschubert/query-tag-action@v2
      with:
        include: 'v*'
        commit-ish: 'HEAD'
        abbrev: false

    - name: Show Tag
      id: display
      run: |
        echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'


    - uses: actions/checkout@v2
      with:
        repository: confinale/medea-config
        ssh-key: '${{ secrets.MEDEA_CONFIG_SSH_KEY }}'
        ref: 'develop'
        path: 'medea-config'

    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.0.4"

    - run: kustomize edit set image confinale/medea:${{steps.tagger.outputs.tag}}
      working-directory: 'medea-config/base'

    - run: | 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Set `confinale/medea` image tag to `${{steps.tagger.outputs.tag}}`"
          git push  
      working-directory: 'medea-config'
