name: Test Across Matrix

on: push

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      ## sets up go based on the version
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...
