name: update deployment config

on:
  create:
  push:
    branches: [ autodeploy ]

jobs:

  get-tag:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Find Tag
      id: tagger
      uses: jimschubert/query-tag-action@v2
      with:
        include: 'v*'
        commit-ish: 'HEAD'
        abbrev: false

    - name: Show Tag
      id: display
      run: |
        echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'


  deploy:

    runs-on: ubuntu-latest
    needs: 'get-tag'

    steps:
    - uses: actions/checkout@v2
      with:
        repository: confinale/medea-config
        #token: ${{ secrets.ACCESS_TOKEN }}
        ref: 'development'
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.0.4"

    - run: kustomize edit set image confinale/medea:${{steps.tagger.outputs.tag}}
      working-directory: 'base'
    - run: git add .
    - run: git commit -m "Set `confinale/medea` image tag to `${{steps.tagger.outputs.tag}}`"
    - run: git push  
